/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Package xml
package xml

import (
	"bytes"
	"io"

	"github.com/iainjreid/dagger"
)

type XML[T any] struct{}

func Fragment[T any](f func(*XML[T]) *dagger.Node[any, XMLNode[T]]) *dagger.Node[any, XMLNode[T]] {
	return f(&XML[T]{})
}

func (s *XML[T]) Attr(name string, fn func(T) string) *dagger.Leaf[any, XMLNode[T]] {
	return Attr(name, fn)
}

func (s *XML[T]) AttrLiteral(name string, f func(T) []byte) *dagger.Leaf[any, XMLNode[T]] {
	return AttrLiteral[T](name, f)
}

func (s *XML[T]) AttrIdentity(name string, value string) *dagger.Leaf[any, XMLNode[T]] {
	return AttrIdentity[T](name, value)
}

func (s *XML[T]) Element(name string) *dagger.Node[any, XMLNode[T]] {
	return Element[T](name)
}

func (s *XML[T]) Text(f func(T) string) *dagger.Leaf[any, XMLNode[T]] {
	return Text[T](f)
}

func (s *XML[T]) TextLiteral(f func(T) []byte) *dagger.Leaf[any, XMLNode[T]] {
	return TextLiteral[T](f)
}

func (s *XML[T]) TextIdentity(name string) *dagger.Leaf[any, XMLNode[T]] {
	return TextIdentity[T](name)
}

type XMLNode[T any] interface {
	WriteTo(Writer, T) (int64, error)

	// Write
	Write(Writer, T)
}

type CollectedWriter struct {
	w   Writer
	n   int64
	err error
}

func NewCollectedWriter(w Writer) *CollectedWriter {
	return &CollectedWriter{
		w: w,
	}
}

func (w *CollectedWriter) Write(p []byte) (int, error) {
	return w.Collect(w.w.Write(p))
}

func (w *CollectedWriter) WriteString(str string) (int, error) {
	return w.Collect(w.w.WriteString(str))
}

func (w *CollectedWriter) Collect(n int, err error) (int, error) {
	w.n += int64(n)

	// TODO: Investigate branchless assignment.
	if err != nil && w.err == nil {
		w.err = err
	}

	return n, err
}

func (w *CollectedWriter) Result() (int64, error) {
	return w.n, w.err
}

// Marshal provides an off-ramp from this library, to the standard library, so
// that code written to handle XML generated by the standard library need not be
// changed.
func Marshal[T any](xml XMLNode[T], data T) ([]byte, error) {
	b := &bytes.Buffer{}
	_, err := xml.WriteTo(b, data)
	return b.Bytes(), err
}

// Marshal provides an off-ramp from this library, to the standard library, so
// that code written to handle XML generated by the standard library need not be
// changed.
func MarshalUnsafe[T any](xml XMLNode[T], data T) []byte {
	b := &bytes.Buffer{}
	xml.Write(b, data)
	return b.Bytes()
}

type Writer interface {
	io.Writer
	io.StringWriter
}
